parameters:
#    shideon_common.example.class: Shideon\Bundle\CommonBundle\Example

services:
#    shideon_common.example:
#        class: %shideon_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
